# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Hm2ubjT5FPYnzcSRWBu8Ina3dGL7L3M
"""
from flask import Flask, request

app = Flask(__name__)

@app.route('/soma', methods=['GET'])
def soma():
    num1 = int(request.args.get('num1'))
    num2 = int(request.args.get('num2'))
    x = num1+num2
    x1 = f"{x}"
    result = ('O resultado da soma é '+x1)
    return result

@app.route('/divisao', methods=['GET'])    
def divisao():
    num1 = int(request.args.get('num1'))
    num2 = int(request.args.get('num2'))
    x = num1/num2
    x1 = f"{x}"
    result = ('O resultado da divisao é '+x1)
    return result
    
@app.route('/subtracao', methods=['GET'])    
def subtracao():
    num1 = int(request.args.get('num1'))
    num2 = int(request.args.get('num2'))
    x = num1-num2
    x1 = f"{x}"
    result = ('O resultado da divisao é '+x1)
    return result

@app.route('/multiplicacao', methods=['GET'])    
def multiplicacao():
    num1 = int(request.args.get('num1'))
    num2 = int(request.args.get('num2'))
    x = num1*num2
    x1 = f"{x}"
    result = ('O resultado da divisao é '+x1)
    return result
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)